### ISSUE TITLE
Should use memory allocation routines that crash on failure, or properly handle allocation failures

### ISSUE THREAD

**Issue by mcatanzaro** [WebPlatformForEmbedded/libwpe#112]
When running cppcheck, Ubuntu Security Team noticed a memory leak if realloc() fails:

```
src/input.c:231:29: error: Common realloc mistake: 'array' nulled but not freed upon failure [memleakOnRealloc]
                            array = (struct wpe_input_xkb_keymap_entry*)realloc(array, array_allocated_size * sizeof(struct wpe_input_xkb_keymap_entry));
```

"If realloc fails, the array pointer will become NULL and the old allocation will be lost (memory leak)." Nowadays this code lives in input-xbc.c, line 234.

Problem is, it's not just here. Other code in libwpe is not prepared for calloc() to fail. It's probably best to switch to memory allocation routines that crash if they fail so you don't have to check every single allocation for failure. I notice libwpe does not depend on GLib, but safer GLib equivalents would be `g_realloc()` or `g_new0()`. Easy enough to write your own wrapper, though.

(Interestingly, I checked wpebackend-fdo and it does not appear to have the same issue.)

**Comment by mcatanzaro** [comment]
Actually even that doesn't matter: WebKit's FastMalloc also crashes on allocation failure. So we should definitely do that.

**Comment by aperezdc** [comment]
> Actually even that doesn't matter: WebKit's FastMalloc also crashes on allocation failure. So we should definitely do that.

Good point.
