### ISSUE TITLE
Archive repo

### ISSUE THREAD

**Issue by ChaseKnowlden** [WebPlatformForEmbedded/libwpe#130]
WebKitGTK 2.44.0 removed the WPE backend.

Link to removal: https://webkitgtk.org/2024/03/16/webkitgtk2.44.0-released.html

**Comment by magomez** [comment]
Those are the release notes for WebKitGTK, which is indeed removing the WPE renderer. But that's not going to be the case for WPE. There will be a new option to use dmabuf as well, but the support to still use libwpe and the backends will still be there.
