### ISSUE TITLE
1.4.0 tarball/build generates version.h for 1.3.91

### ISSUE THREAD

**Issue by philn** [WebPlatformForEmbedded/libwpe#60]
```
cat ../libwpe-1.4.0/DerivedSources/wpe/version.h
...
#define WPE_MAJOR_VERSION (1)
#define WPE_MINOR_VERSION (3)
#define WPE_MICRO_VERSION (91)
...
```

**Comment by philn** [comment]
CMakeLists.txt of the 1.4.0 tarball has `SET_PROJECT_VERSION(1 3 91)`

**Comment by philn** [comment]
Perhaps a brown-paper-bag 1.4.1 release would be good to have @aperezdc ?

**Comment by aperezdc** [comment]
My bad, I did update the version numbers in commit 8789322b68157550421afc178c1b88e13d8f780b but I must have uploaded the tarball resulting from `make distcheck` before doing the commit with the version update (which is the only one missing in the tarball).

I'll make a 1.4.1 release, thanks for the heads up!

**Comment by aperezdc** [comment]
Done, [release 1.4.0.1](https://wpewebkit.org/release/libwpe-1.4.0.1.html) is now available.
