### ISSUE TITLE
tip-of-tree does not compile (cmake configuration failure)

### ISSUE THREAD

**Issue by aslushnikov** [WebPlatformForEmbedded/libwpe#63]
Hi!

I'm trying to compile [tip-of-tree](https://github.com/WebPlatformForEmbedded/libwpe/commit/67ccb407efb295c727553145080937e8bb3a3211) `libwpe` on Ubuntu. I do the following steps:

1. `git clone https://github.com/WebPlatformForEmbedded/libwpe`
2. `cd libwpe`
3. `cmake .`

Here is what I get:

```
aslushnikov:~/prog/libwpe(master)$ cmake .
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CXX_HAS_FLAG_-fno-exceptions
-- Performing Test CXX_HAS_FLAG_-fno-exceptions - Success
-- Performing Test CXX_HAS_FLAG_-fno-rtti
-- Performing Test CXX_HAS_FLAG_-fno-rtti - Success
-- Performing Test CXX_HAS_FLAG_-Wall
-- Performing Test CXX_HAS_FLAG_-Wall - Success
-- Performing Test CC_HAS_FLAG_-Wall
-- Performing Test CC_HAS_FLAG_-Wall - Success
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'egl'
--   Found egl, version 19.2.1
CMake Error at cmake/FindEGL.cmake:53 (target_link_libraries):
  Cannot specify link libraries for target "GL::egl" which is not built by
  this project.
Call Stack (most recent call first):
  CMakeLists.txt:51 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/aslushnikov/prog/libwpe/CMakeFiles/CMakeOutput.log".

```

Note: this worked fine on [version 1.4.0](https://github.com/WebPlatformForEmbedded/libwpe/commit/034900f435735674e003eb6016fc776250630f69); it looks like [this commit](https://github.com/WebPlatformForEmbedded/libwpe/commit/b3e2db9f94dfcae71e5e453f9f28d070651f05ef) changed the EGL discovery somehow and CMake is unhappy.

I tried compiling under clean ubuntu docker image with the same results.

Is this a bug in cmake configuration, or do I miss something?

Thanks!

**Comment by zdobersek** [comment]
Reproduced the same problem.

https://github.com/WebPlatformForEmbedded/libwpe/commit/d395e440883b4b4c764ccd7bae1cf1539d441661 should fix this. AFAIU the error is a quirk of older CMake versions.
