### ISSUE TITLE
How to resovle the issue during build on ubuntu 16.04?

### ISSUE THREAD

**Issue by xushitao000** [WebPlatformForEmbedded/libwpe#87]
During I compile, I encounter varied issue listed below.

------------------------------------------------------------------------
(1)
https://github.com/WebPlatformForEmbedded/libwpe.git  failed with exit code 128, output:
fatal: unable to access 'https://github.com/WebPlatformForEmbedded/libwpe.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.

(2)
Traceback (most recent call last):
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure for URL: 'git://github.com/WebPlatformForEmbedded/libwpe.git;protocol=https;branch=master'. The command git -c core.fsyncobjectfiles=0 ls-remote https://github.com/WebPlatformForEmbedded/libwpe.git  gave empty output unexpectedly

(3)
git -c core.fsyncobjectfiles=0 ls-remote https://github.com/WebPlatformForEmbedded/libwpe.git  failed with exit code 128, output:
fatal: unable to access 'https://github.com/WebPlatformForEmbedded/libwpe.git/': Operation timed out after 0 milliseconds with 0 out of 0 bytes received

(4)
git -c core.fsyncobjectfiles=0 ls-remote https://github.com/WebPlatformForEmbedded/libwpe.git  failed with exit code 128, output:
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: expected flush after ref listing

**Comment by aperezdc** [comment]
This looks like build issues from Bitbake/Yocto…

@xushitao000 Are you are using the [meta-webkit](https://github.com/Igalia/meta-webkit/) Yocto layer?

**Comment by aperezdc** [comment]
@xushitao000 Is this still an issue? Hopefully you have updated to Ubuntu 18.04 or newer, because we do not support 16.04 anymore. I will close this, but please reopen if the issue persist with newer versions.
